furfurylic/commata

include/commata/typing_aid.hpp
Hi. Thank you for developing such a great library!
I met compilation error to build commata/0.2.7 on gcc13:
```
include/commata/typing_aid.hpp:38:39: error: ‘optional’ is not a member of ‘std’
38 | constexpr bool is_std_optional_v<std::optional<T>> = true;
|                                       ^~~~~~~~
include/commata/typing_aid.hpp:11:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
10 | #include <iterator>
+++ |+#include <optional>
11 | #include <string>
include/commata/typing_aid.hpp:38:16: error: parse error in template argument list
38 | constexpr bool is_std_optional_v<std::optional<T>> = true;
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/commata/typing_aid.hpp:38:49: error: expected initializer before ‘>’ token
38 …
```
=> include <optional> header to fix compilation errors on gcc13

include/commata/field_handling.hpp, include/commata/field_scanners.hpp
I met compilation errors in 0.2.9:
```
include/commata/field_scanners.hpp:838:9: error: ‘std::set’ has not been declared
838 |         std::set<string_type, Comp, Allocator2>& c, value_type v)
|         ^~~
include/commata/field_scanners.hpp:838:17: error: expected ‘,’ or ‘...’ before ‘<’ token
838 |         std::set<string_type, Comp, Allocator2>& c, value_type v)
|                 ^
```
It seems to be caused by `field_scanners.hpp`.
https://github.com/furfurylic/commata/blob/master/include/commata/field_scanners.hpp#L838
Please review it.
=> Please include set, functional in 0.2.9

docs/CommataSpecification.xml
`.editorconfig` was introduced to Commata in 1231b43, but it has not been enforced to existing files.
This pull request is to enforce it to the spec (an XML).
=> [Spec] Remove trailing spaces with the force of EditorConfig

docs/CommataSpecification.xml
The definition of _nonconst-direct_ `TableSource` has been wrongly given.
Nonconst `TableSource` shall have its parsers pass **nonconst** char-like objects to table handlers, but it has been not documented.
=> [Bug][Spec] Fix terribly wrong description on nonconst-directness of TableSource

docs/CommataSpecification.xml, include/commata/field_handling.hpp
Remove unnecessary casts from `nullptr`.
=> [Code][Spec] Remove unnecessary casts

docs/CommataSpecification.xml
Fix the description on `ConversionErrorHandler` requirements, in which a now-improper numeral (that is, two) has remained.
=> [Bug][Spec] Take care of a typo

include/commata/detail/base_parser.hpp, include/commata/field_scanners.hpp, include/commata/parse_csv.hpp, include/commata/record_extractor.hpp, include/commata/stored_table.hpp, include/commata/table_pull.hpp, src_test/TestCharInput.cpp, src_test/TestParseCsv.cpp, src_test/TestRecordExtractor.cpp, src_test/TestTablePull.cpp, src_test/TestTableScanner.cpp, src_test/TestTextValueTranslation.cpp, src_test/simple_transcriptor.hpp
Employ `std::string_view`'s literals so that terminating null characters should not be searched for at run time.
In addition, `using` directives for these literals are unified to `using std::string_view_literals;`
=> Employ string_view literals to eradicate strlen-ing of string literals at run time

docs/CommataSpecification.xml
- Fix `HeaderFieldScanner` requirements, which have been telling the way round on constness of its parameters
- Fix the description on `arithmetic_field_translator::operator()`, which have been falsely qualifying its parameters
=> [Bug][Spec] HeaderFieldScanner requirements and arithmetic_field_translator's interface

docs/CommataSpecification.xml, include/commata/char_input.hpp, src_test/TestCharInput.cpp
A resulted range returned by the nonconst-direct interface of a `CharInput` is mandated to be **overwritable even at the past-the-end position.** (To be more precise, the past-the-end element can be overwritable only with a null character.)
So, on the next invocation after a call on the nonconst-direct interface, a `CharInput` must suppose that the first character of its remaining range has been overwritten when it holds one contiguous range of characters.
`owened_string_input` has not had this property. This pull request is to fix this deficiency.
In fact, no further invocations are likely to occur after a call on the nonconst-direct interface on one `CharInput` object, so this deficiency would not do any actual harm. (These further invocations would occur only when the `CharInput` …
=> [Bug] Strictly conform owned_string_input to the CharInput requirements

docs/CommataSpecification.xml, include/commata/char_input.hpp, src_test/TestCharInput.cpp
On a5a9c8e98c5f431239fc3dd5a061371ed235c891, I stated:
> I think make_char_input(indirect, indirect, "ABC") should be equivalent to make_char_input(indirect, "ABC") rather than causing a compilation error, but at this time this is the limit of my efforts
But I found that this is not so difficult and can be achieved with not-that-many diffs. This pull request is to do so.
Strictly speaking, this might not be a bug fix. But this is not likely to cause compatibility issues, nor introducing 'new' features, so I would like to include this diffs to the next bug fix release.
=> Make make_char_input(indirect, indirect, foo) equivalent to make_char_input(indirect, foo)

CMakeLists.txt, docs/CommataSpecification.xml, include/commata/detail/buffer_control.hpp, include/commata/detail/full_ebo.hpp, include/commata/detail/handler_decorator.hpp, include/commata/field_scanners.hpp, include/commata/stored_table.hpp, include/commata/table_scanner.hpp, src_test/CMakeLists.txt
Microsoft [says](https://learn.microsoft.com/en-us/cpp/cpp/empty-bases?view=msvc-170) that Microsoft Visual Studio has limited capability of empty base optimization (EBO) by default. I have not known that.
It seems easy to turn full EBO on, but it breaks ABI compatibility, that is, it can make older object files and newer object files not link. This time it seems better to leave turning full EBO optional on. So, this pull request offers full EBO with `COMMATA_ENABLE_FULL_EBO` macro as its switch.
From now on, the tests are going to be built with `COMMATA_ENABLE_FULL_EBO` defined because the ABI compatibility should not matter the tests.
=> Add COMMATA_ENABLE_FULL_EBO flag to enforce EBO even for MSVC

docs/CommataSpecification.xml, include/commata/field_scanners.hpp, include/commata/text_value_translation.hpp, src_test/TestTableScanner.cpp, src_test/TestTextValueTranslation.cpp
This diff employs so-called 'perfect initialization' for `replace_if_conversion_failed` and `replace_if_skipped`.
This loosens restrictions on the caller of these classes, but does not seem to be an improvement or augmentation on Commata's functionality but a fix on defects of it.
=> Make ctors of replace_if_conversion_failed and replace_if_skipped conditionally explicit

docs/CommataSpecification.xml
The spec has had an unnatural layout on a table on`replace_if_skipped::operator()`.
This has originally resulted from unifying the layout with the table on `replace_if_conversion_failed::operator()`, but now `replace_if_skipped` and `replace_if_conversion_failed` are located far apart in the spec, so this kind of layout-unifying seems no use.
=> Re-adjust column widths of the table on replace_if_skipped::operator()

include/commata/stored_table.hpp
even if its allocator's `select_on_container_copy_construction` returns another allocator because no users will expect that the allocator is replaced after `shrink_to_fit` with a different allocator returned by `select_on_container_copy_construction`.
=> Make basic_stored_table::shrink_to_fit preserve its allocator

docs/CommataSpecification.xml
...reflecting the implementations.
But these defects do not seem grave because when `std::is_convertible_v<const T&, U>` is `true` then the return value of `std::optional<U>` should be made from `std::optional<T>`.
=> [Spec] Fix some minor defects on replace_if_conversion_failed::operator()

include/commata/field_scanners.hpp, src_test/TestTableScanner.cpp
which mistakingly employed an operator less-than in place of `key_comp()`.
=> Take care of a rather fatal bug of string_field_inserter

include/commata/field_scanners.hpp
and mistakingly moves the argument.
In fact, the argument is always an rvalue, so this should be a mere cosmetic issue.
=> Fix a lambda which takes a forwarding reference argument

README.md
I have failed to update README.md so that it should reflect the correct GoogleTest version in #12.
=> [README] Update README.md reflecting the newer GoogleTest version

docs/CommataSpecification.xml
In the spec, so far, an instantiated class from a class template was called an 'instance' of the class template. This pull request fixes it employing 'specialization' in place of 'instance' IAW the specs of C++.
=> Employ the term 'specialization' in place of 'instance' for templates

docs/CommataSpecification.xml, include/commata/table_scanner.hpp
`basic_table_scanner` has two groups of constructors: one takes a header record count, and another takes a HeaderFieldScanner object. The latter was SFINAEd out when the type is not an integral type.
But also a floating point object cannot behave as a HeaderFieldScanner,  so integal-ness does not seem to be the point. This pull request widens the condition of HeaderFieldScanner-taking ctor SFINAEd out so that floating point types should not be treated as HeadeFieldScanner types.
This change seems not to affect existing valid codes.
=> Make HeaderFieldScanner-taking ctors of basic_table_scanner widely SFINAEd out

include/commata/detail/base_source.hpp, include/commata/parse_csv.hpp, include/commata/parse_tsv.hpp
Literally. This pull request is to reduce visibility of some members of `base_source`, which is the base class of `csv_source` and `tsv_source`. The members are ctors, dtor, assignment ops,  and `swap`.
=> Reduce visibility of some members of base_source

include/commata/detail/base_parser.hpp, include/commata/detail/base_source.hpp, include/commata/table_scanner.hpp
Literally. This does not affect the run-time behaviour.
=> Take care of some typos in codes

include/commata/text_error.hpp
This takes care of a boneheaded bug introduced with #38.
=> Remove an excess semicolon

docs/CommataSpecification.xml
`to_arithmetic` ignores trailing white space characters, but the spec did not mention it so far. This pull request is going to fix it.
=> [spec] Reflect the fact that to_arithmetic ignores trailing spaces

include/commata/text_value_translation.hpp
Refactor `raw_converter` so that static member functions and a lambda should be cohered into a function object class.
=> Pull is_space out of raw_converter to avoid code bloat and avoid lambdas

include/commata/detail/base_parser.hpp
Literally. Mainly by reducing repeating long type names.
=> Tidy nested types of base_parser

docs/CommataSpecification.xml, include/commata/parse_csv.hpp, include/commata/parse_tsv.hpp
because the spec *only* mandates that the result type of a parser's invocation shall be contextually convertible to bool
=> Make parse_(c|t)sv cast the return value of the parser

docs/CommataSpecification.xml, include/commata/detail/base_parser.hpp
This pull request does:
- Clearly specify that `TableParser` should throw `parse_error` on parse errors,
- Clearly specify that `TableParser` may wrap exceptions and rethrow them, and
- Make parsers for both of CSV and TSV wrap exceptions in `text_error` to give them the physical position information.
=> Improve parsers' spec and implementation on parse errors

docs/CommataSpecification.xml, include/commata/detail/base_parser.hpp, include/commata/table_pull.hpp, src_test/BaseTest.hpp, src_test/TestTablePull.cpp
So far, `TableParser` optionally have had `get_physical_position`, but its meaning has been not specified clearly.
With this pull request, I would like to introduce a new term 'parse point' to `TableParser` and clearly specify the meaning of `get_physical_position` above.
In the second commit, `get_parse_point` is added to the spec of `TableParser`, its implementations for CSVs and TSVs, and pull parsers (`primitive_table_pull` and `table_pull`). Tests of `table_pull::get_parse_point` are also added.
It is mandatory that `TableParser`s implement the new `get_parse_point`. This is likely to break old codes, to be specific, old parsers written outside of Commata, but I would think this is not a destructive change because defining table parsers other than built-in ones are very rare.
=> Add a term 'parse point' and facilities to access it

include/commata/detail/base_parser.hpp
Commata's built-in parsers (for CSV and TSV) have been wrongly ignoring the return values of `empty_physical_line` of their tied table handlers. This pull request is to fix it.
=> [bug] Make empty_physical_line's return values taken into account

CMakeLists.txt, docs/CommataSpecification.xml, include/commata/detail/base_parser.hpp, include/commata/parse_result.hpp, src_test/TestParseCsv.cpp
With #49, each table parser became accompanied by its intrinsic parse point. This pull request is to make Commata go farther to make table parsers return with or throw with the parse point.
This change imposes more requirements to table parsers, so breaks compatibility of existing external table parsers, but I think that such table parsers are not likely to exist, so I would like to release this in a minor update release.
In the same sense. it could be able to require that table parsers should return a` parse_result` object, but for me it seemed so restrictive, so I keep the requirements at 'to return a `parse_result`-like object'.
=> Make table parsers return/throw with parse point information

docs/CommataSpecification.xml
Change anchors on requirements for built-in parsers added in #51 to more regular ones.
=> [spec] Fix anchors on requirements for built-in parsers

docs/Commata.xsl
Literally.
So far, in the stylesheet of the spec, `pre { line-height: 1.2em }`  has been hidden by `body * { line-height: 1.3em }`. This does not seem desirable (I, however, am not sure because the point of the elaborate selector `body *` is not clear to me any more), so I fix it.
=> [spec] Fix the CSS, whose 'line-height' for 'pre' elements has not been in effect

CommataPrimer.md, docs/CommataSpecification.xml
Literally. It is to clarify points of sentences in the spec that I do so.
As opposed to C++17 standard, I would not like to employ 'i.e.' in place of 'that is' because 'i.e.' is a Latin word and perhaps seems to sound snobbish.
=> [spec][primer] Make all occurrence of 'that is,' enclosed in parens and avoid semicolons

include/commata/field_scanners.hpp, include/commata/text_value_translation.hpp
`nontrivial_store<T>` is derived from `trivial_store<T>`, but it is in the so-called 'in-terms-of' manner, so the inheritance should not be `public`. This pull request reduce its visibility to `private`.
=> Refactor nontrivial_store with reduce visibility of inheritance

docs/CommataSpecification.xml, include/commata/char_input.hpp, src_test/TestCharInput.cpp
The move ctor of `owned_string_input` has been broken. It has missed set a proper value into `front_` and could have made the input corrupted.
On the other hand, the move assignment operator of it has been sound.
I added tests that can detect this buggy behaviour.
=> [bug] Fix bugs in the move ctor of owned_string_input

README.md, src_test/CMakeLists.txt
According to https://github.com/google/oss-policies-info/pull/32, GoogleTest's newest release does not seem to support Microsoft Visual Studio 2019 from 30th Apr 2024 onwards, when its latest release was v1.14.0.
It seems that Commata's tests compile and run well with GoogleTest v1.17.0 and Microsoft Visual Studio 2019, but it is something that is not supported any more. So I would like to downgrade GoogleTest to v1.14.0 for Commata's tests.
=> [test] Downgrade GoogleTest to v1.14.0

docs/CommataSpecification.xml
Literally. Remove (or relax) divergence in the spec from the implementation of `string_field_translator::operator()` taking an rvalue of `std::basic_string`.
=> [spec] Make the spec straightforward in terms of the implementation on string_field_translator

include/commata/detail/base_parser.hpp
Remove `#include "handler_decorator.hpp"` from `"commata/detail/base_parser.hpp"`, which in fact does not reference names declared in `"commata/detail/handler_decorator.hpp"`.
=> Remove unnecessary #include

docs/CommataSpecification.xml
so that it should look like `basic_string::copy`.
=> [spec] Modify the spec of the direct interface of owned_string_input

src_test/TestTextValueTranslation.cpp
Literally. `#include <commata/field_scanners.hpp>` was an unnecessarily wide inclusion and susceptible to changes in built-in field translators.
=> Modify #include in TestTextValueTranslation.cpp

include/commata/detail/allocation_only_allocator.hpp
`allocation_only_allocator::select_on_container_copy_construction`, which returns `allocation_only_allocator`, wrongly made its return value with its base type object. The ctor of `allocation_only_allocator` from its base type object is declared as `explicit` and it is forbidden.
=> [bug] Fix allocation_only_allocator::select_on_container_copy_construction
