- README.md
- src_test/CMakeLists.txt
> Update GoogleTest to v1.15.0

- CommataPrimer.md
> Improve the wording of the primer

- src_test/CMakeLists.txt
> [Test] Update GoogleTest to v1.15.2

- src_test/simple_transcriptor.hpp
Slightly refactor `simple_transcriptor_with_nonconst_interface` class.
> Refactor simple_transcriptor_with_nonconst_interface

- include/commata/stored_table.hpp
Literally. No behavioural change shall not be included.
> Refactor stored_table

- CommataPrimer.md
> [Primer] Fix some styles of Markdown

- include/commata/text_value_translation.hpp
Fixes a bug that seems to be minor.
`ConversionErrorHandler` is required to have a return type convertible to `std::optional<T>`. In the site, we want to check if the return type is convertible to `T` (when it is `std::optional<T>`, the check would not pass), but mistakingly checked if the return type is convertible to `U`, which is a type to which `T` is convertible. This check was too loose, but practically seems not to do any harm.
> Fix a bug in restrained_converter

- include/commata/detail/handler_decorator.hpp
- include/commata/wrapper_handlers.hpp
> Refactor around handler_decorator

- src_test/BaseTest.hpp
...to evade some complexity in defining static member variables of a template class.
> Enclose char_helper::facet_ into a function's local static variable

- include/commata/field_scanners.hpp
- include/commata/stored_table.hpp
> Simplify open braces for namespaces in C++17 style

- docs/CommataSpecification.xml
Literally. No significant semantic changes included.
> [spec] Improve some wording

- include/commata/table_scanner.hpp
- include/commata/text_error.hpp
Slightly improve the style of codes.
> Fix the style of codes

- include/commata/text_error.hpp
This pull request is to reduce occurrences of magic numbers in `text_error.hpp` to improve readability. Additionally, `std::memcpy` is employed in place of `std::snprintf` for performance.
> Refactor text_error_info

- CommataPrimer.md
> [primer] Fix wording in the primer

- include/commata/text_value_translation.hpp
Literally. `raw_converter`'s template param `T` corresponds to `U` of `restrained_converter` for restrained types (for example, `int` for `long`).
> Swap T and U in raw_converter which have been so confusing

- README.md
- src_test/CMakeLists.txt
> [test] Update GoogleTest to v1.16.0

- src_test/TestParseCsv.cpp
- src_test/TestParseTsv.cpp
> Refactor tests

- CommataPrimer.md
Take care of typos in the primer.
> [primer] Fix some wording

- docs/CommataSpecification.xml
> [spec] Minor updates

- docs/CommataSpecification.xml
Refine wording of the description of the CSV/TSV table models.
> [spec] Refine the description of the text models (CSV and TSV)

- src_test/TestCharInput.cpp
This pull request does on `TestCharInput.cpp`:
- cease filling a `char` into an array of `wchar_t`,
- clarify the intention of some test codes, which is to make sure that the return types of `make_char_input` are desirable ones, and
- fix an improper comment.
> [test] Refactor TestCharInput.cpp

- include/commata/table_pull.hpp
...which comprised somewhat too abstruse codes to comprehend.
> Refactor primitive_table_pull

- README.md
- src_test/CMakeLists.txt
> Update GoogleTest to v1.17.0

- docs/CommataSpecification.xml
> [spec][bug] Fix a typo on a ctor of string_view_field_translator

- src_test/TestParseCsv.cpp
- src_test/TestTextError.cpp
> [test] Add static_asserts on nothrowness of exception classes
